version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - app
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=adzura354
      - POSTGRES_USER=postgres
      - POSTGRES_DB=carryme
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: com/carryme:latest
    build:
      context: .
    networks:
      - app
    container_name: springbootapp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/carryme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=adzura354
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:
networks:
  app: